### DISCUSSION TITLE
Reflex-Agent Errors

### DISCUSSION THREAD

**Discussion by ar3diu** [reflexsoar/reflex-api#192] [Q&A]
I can't get Reflex-Agent work in a Docker setup with Reflex-UI, Reflex-API and an Elasticsearch Cluster. 
The only relevant errors I could find: 
```
reflex-ui       | <redacted ip address> - - [15/Jun/2022:13:32:07 +0000] "POST /api/v2.0/agent HTTP/1.1" 409 37 "-" "python-requests/2.27.1" "-"
```
```
reflex-agent    | 2022-06-15 13:24:58,697 - Failed to pair agent. [Errno 13] Permission denied: 'config.txt'
```
As for the first error, I don't understand why it would cause a conflict :man_shrugging:. As for the second error, these are the file permissions: `-rw-r--r-- 1 root root 0 Jun 15 13:08 agent/config.txt`

Other screenshots:
![image](https://user-images.githubusercontent.com/61625853/173821083-6aadcd0c-2b3e-4bb8-842f-c86226df5335.png)
![image](https://user-images.githubusercontent.com/61625853/173819589-e873e44b-1815-4502-921f-30e2009f3f80.png)
![image](https://user-images.githubusercontent.com/61625853/173819647-6b455b34-f5b9-4d0e-a290-6691ecc79d7d.png)
![image](https://user-images.githubusercontent.com/61625853/173819936-00163bfa-02ce-4c6c-808c-6e7d5fde5712.png)

docker-compose.yml _(I have redacted some values by placing them between <>)_:
```
version: '3.7'
services:
  memcached:
    container_name: memcached
    image: hasecuritysolutions/memcached:latest
    command: ["-m", "1024"]
    networks:
      - reflex
    restart: always
    healthcheck:
        test: [ "CMD-SHELL", "echo 'stats' | nc localhost 11211" ]
        interval: 30s
        timeout: 10s
        retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  reflex-api:
    container_name: reflex-api
    environment:
      #- GUNICORN_WORKER_CLASS=gthread
      - REFLEX_ES_URL=<elasticsearch master node>:9200
      - REFLEX_DISABLE_SLAMONITOR=true
      - REFLEX_ES_USERNAME=<service account name>
      - REFLEX_ES_PASSWORD=<service account password>
      - REFLEX_ES_CA=/etc/ssl/certs/<internal ca>.pem
      #- REFLEX_ES_CERT_VERIFY=none
      - REFLEX_ES_AUTH_SCHEMA=http
      - REFLEX_ES_DISTRO=elasticsearch
      - REFLEX_LOG_LEVEL=INFO
      - REFLEX_ES_TIMEOUT=120
      - REFLEX_EVENT_PROCESSOR_ES_BULK_SIZE=250
      - REFLEX_ELASTIC_APM_ENABLED=false
      - REFLEX_THREAT_POLLER_MEMCACHED_ENABLED=true
      - REFLEX_THREAT_POLLER_MEMCACHED_HOST=memcached
      - REFLEX_THREAT_POLLER_MEMCACHED_PORT=11211
      - REFLEX_THREAT_POLLER_MEMCACHED_TTL=60
    image: hasecuritysolutions/reflex-api:version-2022.05.01
    healthcheck:
        test: [ "CMD", "curl", "--silent", "--fail", "http://localhost/api/v2.0/" ]
        interval: 10s
        timeout: 10s
        retries: 10
        start_period: 600s
    volumes:
      - ./application.conf:/instance/application.conf
      - /etc/ssl/certs/<internal ca>.pem:/etc/ssl/certs/<internal ca>.pem
    networks:
      - reflex
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  reflex-ui:
    container_name: reflex-ui
    image: hasecuritysolutions/reflex-ui:version-2022.05.01
    depends_on:
      reflex-api:
        condition: service_healthy
    healthcheck:
        test: [ "CMD", "curl", "--silent", "--fail", "--insecure", "https://localhost" ]
        interval: 10s
        timeout: 10s
        retries: 10
        start_period: 600s
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 443:443
    networks:
      - reflex
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  reflex-agent:
    container_name: reflex-agent
    image: hasecuritysolutions/reflex-agent:version-2022.05.01
    environment:
      - REFLEX_AGENT_PAIR_MODE=true
      - REFLEX_API_HOST=https://reflex-ui
      - REFLEX_AGENT_PAIR_TOKEN=<token value obtained from reflex ui by clicking on New Agent>
      - REFLEX_AGENT_ROLES=runner,poller
      - REFLEX_AGENT_IGNORE_TLS=true
#      - REFLEX_AGENT_GROUPS=
      - REFLEX_AGENT_NAME=reflex-agent-docker
    depends_on:
      reflex-ui:
        condition: service_healthy
    volumes:
      - /opt/reflexsoar/agent/config.txt:/config.txt
      - /opt/reflexsoar/agent:/files
    networks:
      - reflex
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

networks:
  reflex:
```
