### DISCUSSION TITLE
Edit button to change the organization name for a Reflex Agent

### DISCUSSION THREAD

**Discussion by ar3diu** [reflexsoar/reflex-api#202] [Ideas]
In case you want to use Inputs from a new organization, you will need a Reflex Agent assigned to that specific organization _(at least that's my understanding so far)_. But all Reflex Agents are by default assigned to the default organization and there is no edit button so we can change it.

**Comment by ar3diu** [comment]
I tried to change the organization id by modifying the Elasticsearch doc but even though I don't see any errors and the change is reflected in the UI, it doesn't seem to pick up any inputs :man_shrugging:

**Comment by n3tsurge** [comment]
Your assumption is correct but you have to get a pairing token from that organization by logging in as an org admin or going to that orgs settings page as a global tenant and getting that orgs persistent pairing token

Brian Carroll
________________________________
From: Andrei R ***@***.***>
Sent: Tuesday, June 21, 2022 4:32:06 AM
To: reflexsoar/reflex-api ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [reflexsoar/reflex-api] Edit button to change the organization name for a Reflex Agent (Discussion #202)


In case you want to use Inputs from a new organization, you will need a Reflex Agent assigned to that specific organization (at least that's my understanding so far). But all Reflex Agents are by default assigned to the default organization and there is no edit button so we can change it.

**Reply by ar3diu** [reply]
Yeah, that never occurred to me although it does make sense. Thanks for the information!

**Reply by n3tsurge** [reply]
We do have plans for a multi-tenant agent it's just not on the roadmap yet.

**Reply by ar3diu** [reply]
I think the current implementation is sufficient for most cases an MSSP would have... :thinking:

**Reply by n3tsurge** [reply]
For MSSPs, the multi-tenant is more for organizations that may have a single instance of Reflex but have distinct operations teams, they can still leverage a single agent but segregate their data

**Comment by ar3diu** [comment]
So I managed to onboard the agent with the new organization's token. But now I'm trying to pull some alert logs and keep running into this error. I've tried to look in several places like the search query, the inputs config, the service account permissions, docker logs but couldn't identify the issue. The only difference here is that I'm pulling alert logs from a data stream and not from a classic Elasticsearch index.
```
reflex-agent  | 2022-06-21 16:20:38,650 - Running agent
reflex-agent  | 2022-06-21 16:20:38,650 - Running input my_input
reflex-agent  | 2022-06-21 16:20:38,650 - Fetching credentials
reflex-agent  | 2022-06-21 16:20:38,759 - POST https://master-node:9200/data_stream_name_here/_search?scroll=2m [status:200 request:0.015s]
reflex-agent  | 2022-06-21 16:20:38,759 - Found 3 alerts.
reflex-agent  | 2022-06-21 16:20:38,760 - Failed to run search, make sure the Elasticsearch cluster is reachable. 'threat'

```
Also, I have another input assigned to the same agent and no issues seen there. :shrug:

**Reply by n3tsurge** [reply]
So datastream might be the issue we've never tested it with datastreams but i would expect the elastic API response to be the same...let me do some digging here

**Reply by n3tsurge** [reply]
Can you edit the input and share the configuration?  Like this

```
{
    "hosts": [
        "https://localhost:9200"
    ],
    "distro": "opensearch",
    "index": "winlogbeat-*",
    "lucene_filter": "*",
    "cafile": "",
    "scheme": "https",
    "rule_name": "",
    "auth_method": "http_auth",
    "search_size": 200,
    "search_period": "15m",
    "check_hostname": false,
    "severity_field": "",
    "source_reference": "_id",
    "cert_verification": "none",
    "original_date_field": "@timestamp",
    "description_field": "kibana.alert.rule.description",
    "signature_fields": [
        "host.name"
    ],
    "tag_fields": [
        "kibana.alert.rule.tags"
    ]
}
```

**Reply by ar3diu** [reply]
```
{
    "hosts": [
        "elasticsearch01:9200",
        "elasticsearch02:9200",
        "elasticsearch03:9200"
    ],
    "distro": "opensearch",
    "index": "logs-aws.cloudwatch_logs-*",
    "lucene_filter": "tags:falcosidekick",
    "cafile": "/etc/<redacted>",
    "scheme": "https",
    "rule_name": "signal.rule.name",
    "auth_method": "http_auth",
    "search_size": 200,
    "search_period": "15m",
    "check_hostname": false,
    "severity_field": "signal.rule.severity",
    "source_reference": "_id",
    "cert_verification": "none",
    "original_date_field": "@timestamp",
    "description_field": "signal.rule.reason",
    "static_tags": [
        "my_tag"
    ],
    "tag_fields": [
        "kibana.alert.rule.tags"
    ],
    "signature_fields": [
        "signal.rule.name"
    ]
}
```

**Reply by n3tsurge** [reply]
Can you try changing that one to elasticsearch for the distro?  You will also need to update the hosts to start with `https://`

**Reply by ar3diu** [reply]
No success using https for elasticsearch hosts. And if I change the distro type to elasticsearch I run into this error I mentioned before: 
```
reflex-agent  | 2022-06-21 19:27:07,418 - Fetching credentials
reflex-agent  | Traceback (most recent call last):
reflex-agent  |   File "reflex-agent.py", line 99, in <module>
reflex-agent  |     e = Elastic(i['config'], i['field_mapping'], credentials)
reflex-agent  |   File "/utils/elasticsearch.py", line 25, in __init__
reflex-agent  |     self.conn = self.build_es_connection()
reflex-agent  |   File "/utils/elasticsearch.py", line 63, in build_es_connection
reflex-agent  |     return Elasticsearch(self.config['hosts'], **es_config)
reflex-agent  | TypeError: __init__() got an unexpected keyword argument 'scheme'


```

**Reply by n3tsurge** [reply]
i have a sneaking suspicion that your agent container is somehow out of date.  Can you show me your docker-compose.yml section for the reflex-agent?

**Reply by ar3diu** [reply]
I thought version-2022.05.01 is the latest one. Should I change it to `:latest`?

```
  reflex-agent:
    container_name: reflex-agent
    image: hasecuritysolutions/reflex-agent:version-2022.05.01
    environment:
      - REFLEX_AGENT_PAIR_MODE=true
      - REFLEX_API_HOST=https://reflex-ui
      - REFLEX_AGENT_PAIR_TOKEN=
      - REFLEX_AGENT_ROLES=runner,poller
      - REFLEX_AGENT_IGNORE_TLS=true
      - REFLEX_AGENT_GROUPS=
      - REFLEX_AGENT_NAME=reflex-agent
    depends_on:
      reflex-ui:
        condition: service_healthy
    volumes:
      - /opt/reflexsoar/agent/config.txt:/config.txt
      - /opt/reflexsoar/agent:/files
      - /etc/ssl/certs/<>.pem:/etc/ssl/certs/<>.pem
    networks:
      - reflex
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

```
