### ISSUE TITLE
Issue configuring my OpenSearch as backend

### ISSUE THREAD

**Issue by greycel** [reflexsoar/reflex-api#405]
Hi Everyone,

Wanted to configure and use my OpenSearch as the backend persistent storage for Reflex.

Followed docker steps as per ```https://github.com/reflexsoar/reflex-api#docker``` which has used a different image ```zeroonesec/reflex-api:elastic-backend``` 

Got stuck in ```step-7``` as I couldn't bring the reflex-api containers up and running, getting below error:
<img width="1674" alt="image" src="https://github.com/reflexsoar/reflex-api/assets/11851504/e018f68c-bf0f-4300-bbe6-5e3a1aa7d5a8">

Any steps on how to proceed with configuring the existing OpenSearch instance as the persistent storage would be greatly helpful...

**Comment by n3tsurge** [comment]
Any documentation you see in Github is out of date.  You would simply need to change the docker-compose settings for reflex-api that were created during the quickstart to point at your cluster instead of the one created during quickstart.   The image you pulled was a migration build and is not a prod release.  All your images should use `version-2022.06.00` as their tag at this time.

``` version: '3.7'

services:
  reflex-api:
    environment:
      - REFLEX_ES_URL=es01:9200
      - REFLEX_ES_USERNAME=admin
      - REFLEX_ES_PASSWORD=password
      - REFLEX_ES_DISTRO=opensearch
      - REFLEX_ES_CA=/ca.crt
      - REFLEX_ES_CERT_VERIFY=true
    image: zeroonesec/reflex-api:version-2022.06.00
    container_name: reflex-api
    volumes:
      - ./application.conf:/instance/application.conf
      - ./ca.crt:/ca.crt

  reflex-ui:
    image: zeroonesec/reflex-ui:version-2022.06.00
    container_name: reflex-ui
    ports:
      - 80:80
      - 443:443
 ```

**Comment by greycel** [comment]
I've made changes to the docker-compose.yml that's generated with the quick-start install, but I couldn't bring it up yet due to issues with permission.
<img width="1411" alt="Screenshot 2023-06-07 at 7 45 43 AM" src="https://github.com/reflexsoar/reflex-api/assets/11851504/0e9778ed-0dd7-48ae-825b-65afff75e6cd">

A couple of things would like to understand while configuring my OpenSearch as persistent storage:
1) There are YML files ``` internal_users.yml, roles.yml, roles_mapping.yml, action_groups.yml, nodes_dn.yml, whitelist.yml, config.yml``` as volume mounts in ```docker-compose.yml file``` for OpenSearch docker instance. 
        - How to use these YML with my OpenSearch instance...?

2) During the setup, there are new indices created that begin with ```reflex-*``` in the OpenSearch docker instance. 
       - Is there a script that can connect to my OpenSearch and make the required configuration specified...?  
       - Or any manual steps that I can follow to get my OpenSearch configured and running...?
3) What permissions are needed by reflex-SOAR in OpenSearch for it to work..?


Thank you for your time, really appreciate it...

**Comment by n3tsurge** [comment]
From that error it appears you don't have the correct opensearch username and password in the configuration, so I would check your credentials.  If you want to start from scratch, follow the steps below.

## Manual Startup Steps

1) Stop all your quickstart containers
2) Create a new folder for reflex
3) Create a new file called application.conf and put the following in it

```ini
MASTER_PASSWORD = "somethingdifferentthanthesecretkey"
SECRET_KEY = "pleasechangemetosomethingdifferent"
SECURITY_PASSWORD_SALT = "something_super_secret_change_in_production"
```

4) Create a new `docker-compose.yml` file with the below YAML

```yaml
services:
  reflex-api:
    environment:
      - REFLEX_ES_URL=es01:9200
      - REFLEX_ES_USERNAME=admin
      - REFLEX_ES_PASSWORD=password
      - REFLEX_ES_DISTRO=opensearch
      - REFLEX_ES_CA=/ca.crt
      - REFLEX_ES_CERT_VERIFY=true
    image: zeroonesec/reflex-api:version-2022.06.00
    container_name: reflex-api
    volumes:
      - ./application.conf:/instance/application.conf
      - ./ca.crt:/ca.crt

  reflex-ui:
    image: zeroonesec/reflex-ui:version-2022.06.00
    container_name: reflex-ui
    ports:
      - 80:80
      - 443:443
```

5) Update it with your opensearch credential details
6) Update it with the proper path to the previously created `application.conf` file
7) If you have a ca cert make sure its path is correct in `docker-compose.yml`
8) Change es01 to your opensearch hostnames
9) Start reflex using `docker-compose up`
10) Reflex will automatically create all the required indices, and the default admin (admin@reflexsoar.com/reflex)
11) Navigate to https://yourservername/ and login

**Comment by greycel** [comment]
I couldn't bring up ```reflex-api``` container, getting the below error when attempting to setup with suggested configurations:

![image](https://github.com/reflexsoar/reflex-api/assets/11851504/9f9269f0-35e9-409d-b0f0-85e1fee139a1)

**Comment by n3tsurge** [comment]
Can you share your docker compose file with me please

**Comment by greycel** [comment]
Here is the compose file, I've added ```memcached``` section

```
services:
  memcached:
    container_name: memcached
    image: hasecuritysolutions/memcached:6.21.2022
    command: ["-m", "1024"]
    networks:
      - reflex
    healthcheck:
        test: [ "CMD-SHELL", "echo 'stats' | nc localhost 11211" ]
        interval: 30s
        timeout: 10s
        retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  reflex-api:
    environment:
      - REFLEX_ES_URL=192.168.11.145:9200
      - REFLEX_ES_USERNAME=ES_USER
      - REFLEX_ES_PASSWORD=ES_PASSWORD
      - REFLEX_ES_DISTRO=opensearch
#      - REFLEX_ES_CA=/ca.crt
      - REFLEX_ES_CERT_VERIFY=true
    image: zeroonesec/reflex-api:version-2022.06.00
    container_name: reflex-api
    volumes:
      - ./config/application.conf:/instance/application.conf
      - ./config/ca.crt:/ca.crt
    networks:
      - reflex
  reflex-ui:
    image: zeroonesec/reflex-ui:version-2022.06.00
    container_name: reflex-ui
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - reflex
    ports:
      - 443:443

networks:
  reflex:

```
